#! /bin/sh

##---------- Autostart ----------##

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Merge XRresources
xrdb -merge ~/.Xresources &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Scratchpad
st -c scratchterm &
# Wallpaper
nitrogen --restore &
# Clipmenu
/usr/bin/clipmenud &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# Nvidia Settings
nvidia-settings --load-config-only &
# Picom
picom -CGb &
# Polybar
~/.config/bspwm/polybar/launch.sh &
# Cursor
xsetroot -cursor_name left_ptr &

# Dual Monitor Setup
bspc monitor DP-2 -d 1 2 3 4 5 6 7
bspc monitor HDMI-0 -d 8 9 10

##---------- Bspwm Settings ----------##
#bspc config automatic_scheme spiral
#bspc config initial_polarity first_child
#bspc config pointer_modifier shift
bspc config border_width         1
bspc config window_gap          6
bspc config split_ratio          0.5
#bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

##---------- Colors ----------##

# Old colors
#bspc config focused_border_color        "#6c71c4"
#bspc config normal_border_color         "#073642"
#bspc config active_border_color         "#073642"

# Gruvbox Theme
bspc config normal_border_color	"#504945"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#83a598"
bspc config presel_feedback_color	"#83a598"
bspc config urgent_border_color "#fb4934"


##---------- Rules for Apps ----------##

# Remove all rules 
bspc rule -r *:*

# Desktop 1
bspc rule -a Xfce4-terminal desktop='^1' follow=on

# Desktop 2
bspc rule -a Brave-browser desktop='^2' follow=on

# Desktop 3
bspc rule -a Thunar desktop='^3' follow=on

# Desktop 4
bspc rule -a Xed desktop='^4' follow=on
bspc rule -a Zathura desktop='^4' follow=on state=tiled

# Desktop 5
bspc rule -a Io.github.celluloid_player.Celluloid desktop='^5' follow=on

# Desktop 6


# Desktop 7

# Desktop 8
bspc rule -a firefox desktop='^8' follow=on state=tiled

# Desktop 9
bspc rule -a TelegramDesktop desktop='^9' follow=on

# Desktop 10
bspc rule -a Transmission-gtk desktop='^10' follow=on

# Special rules
bspc rule -a Galculator state=floating
bspc rule -a scratchterm sticky=on state=floating hidden=on
