#! /bin/sh

##---------- Autostart ----------##

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Higher rate
xset r rate 300 50 &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# Polybar
~/.config/bspwm/polybar/launch.sh &


# Dual Monitor Setup
bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 10

##---------- Bspwm Settings ----------##

bspc config border_width         1
bspc config window_gap          6
bspc config split_ratio          0.52
#bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

##---------- Colors ----------##

# Old colors
#bspc config focused_border_color        "#6c71c4"
#bspc config normal_border_color         "#073642"
#bspc config active_border_color         "#073642"

# Gruvbox Theme
bspc config normal_border_color	"#504945"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#83a598"
bspc config presel_feedback_color	"#83a598"
bspc config urgent_border_color "#fb4934"


##---------- Rules for Apps ----------##

# Remove all rules 
bspc rule -r *:*

# Desktop 1
bspc rule -a Xfce4-terminal desktop='^1' follow=on

# Desktop 2
bspc rule -a Brave-browser desktop='^2' follow=on

# Desktop 3
bspc rule -a Thunar desktop='^3' follow=on

# Desktop 4
bspc rule -a Xed desktop='^4' follow=on

# Desktop 5
bspc rule -a Zathura desktop='^5' follow=on state=tiled
bspc rule -a Io.github.celluloid_player.Celluloid desktop='^5' follow=on

# Desktop 6
bspc rule -a firefox desktop='^6' follow=on state=tiled

# Desktop 7

# Desktop 8

# Desktop 9
bspc rule -a TelegramDesktop desktop='^9' follow=on

# Desktop 10
bspc rule -a Transmission-gtk desktop='^10' follow=on

# Special rules
bspc rule -a Galculator state=floating
